"""Build a self-contained HTML "receipt" of a generated wiki page.

One file a judge can open: prose with citations that expand to the actual source lines
on click, plus a grounding ledger (claim -> span -> supported?) and a "what we refused
to say" section (sentences the fail-closed loop dropped). This is the differentiator:
refusal, inspectable, in one artifact.

Usage: python -m repowiki.showcase <repo> --wiki-dir <generated> --page overview.md \
          --out showcase/<repo>.html
"""
from __future__ import annotations

import argparse
import html
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from repowiki.claim_extract import claims_from_body          # noqa: E402
from repowiki.index import build_index                        # noqa: E402
from repowiki.ingest import ingest                            # noqa: E402

CITE_RX = re.compile(r"`([A-Za-z_][\w.]*)`\s*\(`([A-Za-z0-9_\-./]+\.\w+):(\d+)-(\d+)`\)")


def build_showcase(repo_src: str, wiki_dir: Path, page: str, out: Path,
                   claims_report: dict | None = None) -> Path:
    idx = build_index(ingest(repo_src))
    body = (wiki_dir / page).read_text(encoding="utf-8")
    title = page.replace(".md", "").replace("-", " ").title()

    # split body into segments, replacing citations with expandable spans
    parts = []
    last = 0
    claims = claims_from_body(body)
    claim_map = {c["claim"][:60]: c for c in claims}
    for m in CITE_RX.finditer(body):
        parts.append(("text", body[last:m.start()]))
        name, path, a, b = m.group(1), m.group(2), int(m.group(3)), int(m.group(4))
        excerpt = idx.content_at(path, a, b)
        if len(excerpt) > 1500:
            excerpt = excerpt[:1500] + "\n…"
        parts.append(("cite", {"name": name, "loc": f"{path}:{a}-{b}", "code": excerpt}))
        last = m.end()
    parts.append(("text", body[last:]))

    # render
    css = """
    body{font-family:system-ui,sans-serif;max-width:860px;margin:40px auto;padding:0 20px;
         background:#0d1117;color:#dbe2ea;line-height:1.6}
    h1{color:#58a6ff;border-bottom:1px solid #30363d;padding-bottom:8px}
    h2{color:#58a6ff;margin-top:32px}
    code{background:#161b22;padding:2px 6px;border-radius:4px;font-family:ui-monospace,monospace}
    .cite{cursor:pointer;color:#7ee787;border-bottom:1px dashed #7ee787}
    .cite:hover{background:#1f6feb33}
    .popover{display:none;background:#161b22;border:1px solid #30363d;border-radius:8px;
             padding:14px;margin:8px 0;font-family:ui-monospace,monospace;font-size:12.5px;
             white-space:pre;overflow-x:auto;color:#a5d6ff}
    .popover.open{display:block}
    .loc{color:#8b949e;font-size:11px}
    #ledger{margin-top:48px;border-top:2px solid #30363d;padding-top:16px}
    .ok{color:#3fb950}.part{color:#d29922}.bad{color:#f85149}
    .dropped{color:#8b949e;text-decoration:line-through}
    """
    js = """
    function toggle(el){el.nextElementSibling.classList.toggle('open')}
    """
    out_html = [f"<html><head><meta charset=utf-8><title>repowiki: {title}</title>",
                f"<style>{css}</style></head><body>",
                f"<h1>{title}</h1>",
                f"<p><em>Generated by repowiki. Every citation below is expandable — "
                f"click to see the exact source lines.</em></p>"]
    for kind, payload in parts:
        if kind == "text":
            # markdown-ish to html (light)
            seg = html.escape(payload)
            seg = re.sub(r"^# (.+)$", r"<h2>\1</h2>", seg, flags=re.M)
            seg = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", seg)
            out_html.append(seg.replace("\n", "<br>\n"))
        else:
            c = payload
            out_html.append(
                f'<span class="cite" onclick="toggle(this)"><code>{html.escape(c["name"])}</code>'
                f' <span class="loc">({html.escape(c["loc"])})</span></span>'
                f'<div class="popover">{html.escape(c["code"])}</div>')
    # grounding ledger
    out_html.append('<div id="ledger"><h2>Grounding ledger</h2>'
                    '<p>Every claim on this page, the span it cites, and whether the '
                    'cited code supports it (independently judged).</p>')
    if claims_report and claims_report.get("verdicts"):
        for v in claims_report["verdicts"]:
            cls = {"SUPPORTED": "ok", "PARTIAL": "part"}.get(v["verdict"], "bad")
            out_html.append(
                f'<div><span class="{cls}">[{v["verdict"]}]</span> '
                f'{html.escape(v["claim"][:120])} <span class="loc">'
                f'{html.escape(v["file"])}:{v["a"]}-{v["b"]}</span></div>')
    else:
        for c in claims:
            out_html.append(
                f'<div><span class="ok">[cited]</span> {html.escape(c["claim"][:120])} '
                f'<span class="loc">{c["file"]}:{c["a"]}-{c["b"]}</span></div>')
    out_html.append("</div>")
    out_html.append(f"<script>{js}</script></body></html>")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(out_html), encoding="utf-8")
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("repo")
    ap.add_argument("--wiki-dir", required=True)
    ap.add_argument("--page", default="overview.md")
    ap.add_argument("--out", required=True)
    ap.add_argument("--claims-report", default=None)
    args = ap.parse_args()
    claims_report = None
    if args.claims_report and Path(args.claims_report).exists():
        claims_report = json.loads(Path(args.claims_report).read_text())
    out = build_showcase(args.repo, Path(args.wiki_dir), args.page, Path(args.out),
                         claims_report)
    print(f"[showcase] wrote {out}")


if __name__ == "__main__":
    main()
